version: "3"

services:
  mariadb:
    container_name:
      mariadb
    build:
      context: requirements/mariadb
      dockerfile : Dockerfile
      args :
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: unless-stopped
    networks:
      - inception
    volumes:
      - .:/var/lib/mysql/data

  wordpress:
    container_name:
      wordpress
    depends_on:
      - mariadb
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
      args:
        HOST: "mariadb"
        USER: ${MYSQL_USER}
        PASS: ${MYSQL_PASSWORD}
        DATABASE: ${MYSQL_DATABASE}
    restart: unless-stopped
    networks: 
      - inception
    volumes:
      - .:/var/www/html

#  nginx:
 #   container_name: nginx
  #  depends_on:
   #   - wordpress
    #ports:
     # - "443:443"
#    build:
 #     context: requirements/nginx
  #    dockerfile: Dockerfile
   # restart: unless-stopped
    #networks: 
     # - inception
    #volumes:
     # - .:/var/www/html
    

volumes:
  wordpressvolume:
    driver: local 
  mariadbvolume:
    driver: local


networks:
  inception:
    driver: bridge